# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5546\u5e97')),
                ('address', models.CharField(max_length=255, verbose_name='\u5546\u5e97\u5730\u5740')),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Lat')),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Lng')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='\u5546\u54c1\u540d')),
                ('price', models.FloatField(verbose_name='\u552e\u4ef7')),
                ('status', models.CharField(choices=[(b'new', '\u65b0\u589e\u5546\u54c1'), (b'pending_review', '\u5f85\u5ba1\u6838'), (b'human_verified', '\u5df2\u901a\u8fc7\u4eba\u5de5\u5ba1\u6838'), (b'auto_verified', '\u5df2\u901a\u8fc7\u81ea\u52a8\u5ba1\u6838'), (b'no_matches', '\u6ca1\u6cd5\u5339\u914d')], default=b'under_review', max_length=255, verbose_name='\u72b6\u6001')),
                ('disambiguation_detail', models.TextField(blank=True, null=True, verbose_name='\u5339\u914d\u8be6\u60c5')),
                ('trade_at', models.DateTimeField(verbose_name='\u751f\u6210\u65e5\u671f')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('standard_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='standard.StandardItem', verbose_name='\u6807\u51c6\u5316\u5546\u54c1')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
        ),
    ]
