# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullAccessStoreItem',
            fields=[
            ],
            options={
                'verbose_name': '\u6240\u6709\u5546\u54c1',
                'proxy': True,
                'verbose_name_plural': '\u6240\u6709\u5546\u54c1',
            },
            bases=('store.storeitem',),
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '\u4fbf\u5229\u5e97', 'verbose_name_plural': '\u4fbf\u5229\u5e97'},
        ),
        migrations.AlterModelOptions(
            name='storeitem',
            options={'verbose_name': '\u5f85\u5ba1\u6838\u5546\u54c1', 'verbose_name_plural': '\u5f85\u5ba1\u6838\u5546\u54c1'},
        ),
        migrations.AddField(
            model_name='storeitem',
            name='receipt_item_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='\u5c0f\u7968\u5546\u54c1ID'),
        ),
    ]
