# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160530_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeitem',
            options={'verbose_name': '\u5546\u54c1', 'verbose_name_plural': '\u5546\u54c1'},
        ),
    ]
