# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160616_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('level', models.CharField(max_length=255, verbose_name='\u5c42')),
                ('parent_id', models.SmallIntegerField(verbose_name='\u7236\u5c42')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='city_path',
            field=models.CharField(default='', max_length=100, verbose_name='\u57ce\u5e02 ID \u8def\u5f84'),
            preserve_default=False,
        ),
    ]
