# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20160616_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='level',
            field=models.SmallIntegerField(verbose_name='\u5c42'),
        ),
    ]
