# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20160616_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '\u7701\uff0f\u5e02\uff0f\u5340', 'verbose_name_plural': '\u7701\uff0f\u5e02\uff0f\u5340'},
        ),
        migrations.AddField(
            model_name='store',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 21, 11, 17, 47, 576419, tzinfo=utc), verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='num_na',
            field=models.PositiveIntegerField(default=0, verbose_name='\u975e\u6807\u54c1\u6570'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='num_new_items',
            field=models.PositiveIntegerField(default=0, verbose_name='\u65b0\u54c1\u6570'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='num_pending_items',
            field=models.PositiveIntegerField(default=0, verbose_name='\u5f85\u5ba1\u6838\u5546\u54c1\u6570'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='num_sku',
            field=models.PositiveIntegerField(default=0, verbose_name='SKU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='num_verified_items',
            field=models.PositiveIntegerField(default=0, verbose_name='\u6807\u54c1\u6570'),
            preserve_default=False,
        ),
    ]
