# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20160621_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='complete_rate',
            field=models.FloatField(default=0, verbose_name='\u5b8c\u6210\u5ea6'),
            preserve_default=False,
        ),
    ]
