# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20160622_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='opeartor',
            new_name='operator',
        ),
    ]
