# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20160623_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filteredstoreitem',
            options={'verbose_name': '\u6240\u6709\u5546\u54c1', 'verbose_name_plural': '\u6240\u6709\u5546\u54c1'},
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='status',
            field=models.CharField(choices=[(b'new', '\u65b0\u589e\u5546\u54c1'), (b'pending_review', '\u5f85\u5ba1\u6838'), (b'human_verified', '\u5df2\u901a\u8fc7\u4eba\u5de5\u5ba1\u6838'), (b'auto_verified', '\u5df2\u901a\u8fc7\u81ea\u52a8\u5ba1\u6838'), (b'no_matches', '\u6ca1\u6cd5\u5339\u914d'), (b'na', '\u975e\u6807\u51c6\u54c1'), (b'error', '\u6570\u636e\u6709\u8bef')], default=b'under_review', max_length=255, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterUniqueTogether(
            name='storeitem',
            unique_together=set([('store', 'name')]),
        ),
    ]
