# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 02:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20160705_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u4eba\u7fa4')),
            ],
            options={
                'verbose_name': '\u8986\u76d6\u4eba\u7fa4',
                'verbose_name_plural': '\u8986\u76d6\u4eba\u7fa4',
            },
        ),
        migrations.CreateModel(
            name='StoreTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u5546\u5e97\u6807\u7b7e',
                'verbose_name_plural': '\u5546\u5e97\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5546\u5e97\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u5546\u5e97\u7c7b\u578b',
                'verbose_name_plural': '\u5546\u5e97\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='TradingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5546\u5708')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_areas', to='store.City', verbose_name='\u57ce\u5e02')),
            ],
            options={
                'verbose_name': '\u5546\u5e97\u5546\u5708',
                'verbose_name_plural': '\u5546\u5e97\u5546\u5708',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='bussiness_hours',
            field=models.CharField(blank=True, choices=[(b'day', '\u65e5\u8425\u4e1a'), (b'24hours', '24\u5c0f\u65f6')], max_length=20, null=True, verbose_name='\u8425\u4e1a\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8054\u7cfb\u4eba'),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8054\u7cfb\u4eba\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='store',
            name='customer_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='\u8986\u76d6\u4eba\u7fa4'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_scale',
            field=models.CharField(blank=True, choices=[(b'convenience_store', '\u4fbf\u5229\u5e97'), (b'community_store', '\u793e\u533a\u5e97'), (b'supermarket', '\u6807\u8d85')], max_length=100, null=True, verbose_name='\u5546\u5e97\u89c4\u6a21'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), null=True, size=None, verbose_name='\u5546\u5e97\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='store',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='store',
            name='num_na',
            field=models.PositiveIntegerField(verbose_name='\u4e0d\u5904\u7406\u5546\u54c1\u6570'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='status',
            field=models.CharField(choices=[(b'new', '\u65b0\u589e\u5546\u54c1'), (b'pending_review', '\u5f85\u5ba1\u6838'), (b'human_verified', '\u5df2\u901a\u8fc7\u4eba\u5de5\u5ba1\u6838'), (b'auto_verified', '\u5df2\u901a\u8fc7\u81ea\u52a8\u5ba1\u6838'), (b'no_matches', '\u6ca1\u6cd5\u5339\u914d'), (b'na', '\u4e0d\u5904\u7406'), (b'error', '\u6570\u636e\u6709\u8bef')], default=b'under_review', max_length=255, verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='store',
            name='trading_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.TradingArea', verbose_name='\u5546\u5e97\u5546\u5708'),
        ),
        migrations.AlterUniqueTogether(
            name='tradingarea',
            unique_together=set([('city', 'name')]),
        ),
    ]
