# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20160711_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreType',
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '\u5546\u5e97', 'verbose_name_plural': '\u5546\u5e97'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_types',
        ),
        migrations.AlterField(
            model_name='customertype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u4eba\u7fa4'),
        ),
        migrations.AlterField(
            model_name='storetag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('name', 'level', 'parent_id')]),
        ),
    ]
