# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20160711_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='receipt_pritin_freq',
            field=models.CharField(blank=True, choices=[(b'all', '\u5168\u90e8'), (b'often', '\u7ecf\u5e38'), (b'occasionally', '\u5076\u5c14')], max_length=100, null=True, verbose_name='\u5546\u5e97\u89c4\u6a21'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_scale',
            field=models.CharField(blank=True, choices=[(b'small', '\u5c0f\u578b\u8d85\u5e02'), (b'medium', '\u4e2d\u578b\u8d85\u5e02'), (b'big', '\u5927\u578b\u8d85\u5e02'), (b'super', '\u767e\u8d27\u8d85\u5e02')], max_length=100, null=True, verbose_name='\u5546\u5e97\u89c4\u6a21'),
        ),
    ]
