# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20160711_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='receipt_pritin_freq',
            new_name='receipt_priting_freq',
        ),
    ]
