# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20160711_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='receipt_printing_freq',
            field=models.CharField(blank=True, choices=[(b'all', '\u5168\u90e8'), (b'often', '\u7ecf\u5e38'), (b'occasionally', '\u5076\u5c14')], default=b'all', max_length=100, null=True, verbose_name='\u6253\u7968\u983b\u6b21'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set([('name', 'city_path')]),
        ),
    ]
