# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20160711_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='store',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Lng'),
        ),
    ]
