# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 05:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20160711_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='\u5173\u952e\u8bcd'),
        ),
        migrations.AlterField(
            model_name='store',
            name='receipt_printing_freq',
            field=models.CharField(blank=True, choices=[(b'all', '\u6240\u6709'), (b'often', '\u7ecf\u5e38'), (b'occasionally', '\u5076\u5c14')], default=b'all', max_length=100, null=True, verbose_name='\u6253\u7968\u983b\u6b21'),
        ),
    ]
