# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 08:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20160715_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), null=True, size=None, verbose_name='Vector'),
        ),
    ]
