# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0030_standardcompany_vector'),
        ('store', '0023_storeitem_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCompanyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_rate', models.FloatField(default=0, verbose_name='\u5b8c\u6210\u5ea6')),
                ('num_sku', models.PositiveIntegerField(default=0, verbose_name='SKU')),
                ('num_new_items', models.PositiveIntegerField(default=0, verbose_name='\u65b0\u54c1\u6570')),
                ('num_pending_items', models.PositiveIntegerField(default=0, verbose_name='\u5f85\u5ba1\u6838\u5546\u54c1\u6570')),
                ('num_na', models.PositiveIntegerField(default=0, verbose_name='\u4e0d\u5904\u7406\u5546\u54c1\u6570')),
                ('num_verified_items', models.PositiveIntegerField(default=0, verbose_name='\u6807\u54c1\u6570')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65e5\u671f')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stats', to='standard.StandardCompany', verbose_name='\u54c1\u724c')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
            options={
                'verbose_name': '\u5546\u5e97\u54c1\u724c\u9032\u5ea6',
                'verbose_name_plural': '\u5546\u5e97\u54c1\u724c\u9032\u5ea6',
            },
        ),
        migrations.AlterUniqueTogether(
            name='storecompanystats',
            unique_together=set([('store', 'company')]),
        ),
    ]
