# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20160716_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storecompanystats',
            old_name='num_new_items',
            new_name='num_new',
        ),
    ]
