# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_storeitem_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='disambiguation_detail',
        ),
    ]
