# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_storeitem_disambiguation_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.PositiveIntegerField(default=0, verbose_name='StoreID'),
            preserve_default=False,
        ),
    ]
