# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20160805_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='\u540d\u79f0')),
                ('type', models.CharField(choices=[(b'convenience_store', '\u4fbf\u5229\u5e97'), (b'supermarket', '\u8d85\u5e02'), (b'mall', '\u8d2d\u7269\u4e2d\u5fc3'), (b'bank', '\u94f6\u884c'), (b'airport', '\u673a\u573a'), (b'train_station', '\u706b\u8f66\u7ad9'), (b'subway_station', '\u5730\u94c1\u7ad9'), (b'hospital', '\u533b\u9662'), (b'park', '\u516c\u56ed'), (b'entertainment', '\u5a31\u4e50\u573a\u6240'), (b'hotel', '\u9152\u5e97'), (b'restaurant', '\u9910\u5385'), (b'library', '\u56fe\u4e66\u9986'), (b'primary_school', '\u5c0f\u5b66'), (b'middle_school', '\u4e2d\u5b66'), (b'university', '\u5927\u5b66'), (b'office_building', '\u5199\u5b57\u697c'), (b'community', '\u5bb6\u5c5e\u533a'), (b'enterprise', '\u516c\u53f8'), (b'government', '\u653f\u5e9c'), (b'internal_building', '\u5185\u90e8\u5efa\u7b51')], default=b'convenience_store', max_length=30, verbose_name='\u7c7b\u522b')),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Lat')),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Lng')),
                ('address', models.CharField(max_length=512, verbose_name='\u5730\u5740')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='\u7535\u8bdd')),
            ],
            options={
                'verbose_name': '\u5b9e\u4f53\u5e97',
                'verbose_name_plural': '\u5b9e\u4f53\u5e97',
            },
        ),
    ]
