# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='adcode',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='\u533a\u57df\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='city',
            name='polyline',
            field=models.TextField(blank=True, null=True, verbose_name='\u533a\u57df\u8fb9\u754c'),
        ),
        migrations.AddField(
            model_name='entity',
            name='amap_id',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='\u9ad8\u5fb7\u5730\u56feID'),
        ),
        migrations.AddField(
            model_name='entity',
            name='baidu_map_id',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='\u767e\u5ea6\u5730\u56feID'),
        ),
        migrations.AddField(
            model_name='entity',
            name='city_path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u57ce\u5e02 ID \u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, max_length=512, verbose_name='\u5730\u5740'),
        ),
    ]
