# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20160919_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeshelf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.store_shelf_upload, verbose_name='\u8d27\u67b6\u56fe'),
        ),
    ]
