# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20160901_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='adcode',
            field=models.CharField(max_length=20, null=True, verbose_name='\u533a\u57df\u7f16\u53f7'),
        ),
    ]
