# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_storeshelf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.store_item_upload, verbose_name='\u5546\u54c1\u56fe'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='\u5546\u54c1\u56feURL'),
        ),
    ]
