# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20160901_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='amap_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='\u9ad8\u5fb7\u5730\u56feID'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='baidu_map_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='\u767e\u5ea6\u5730\u56feID'),
        ),
    ]
