# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20160921_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city_path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u57ce\u5e02 ID \u8def\u5f84'),
        ),
    ]
