# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20160901_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u7535\u8bdd'),
        ),
    ]
