# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20160921_1817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set([]),
        ),
    ]
