# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20160901_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialed', models.BooleanField(default=False, verbose_name='\u662f\u5426\u62e8\u901a\u7535\u8bdd')),
                ('has_pos', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6709POS\u673a')),
                ('entirely_print', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5168\u90e8\u6253\u5370')),
                ('printer_installed', models.BooleanField(default=False, verbose_name='\u662f\u5426\u88c5\u914d\u6253\u5370\u673a')),
                ('postscript', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('entity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_entity', to='store.Entity', verbose_name='\u5408\u4f5c\u5546\u5e97')),
            ],
        ),
    ]
