# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_cooperativeentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperativeentity',
            options={'verbose_name': '\u5408\u4f5c\u5546\u5bb6', 'verbose_name_plural': '\u5408\u4f5c\u5546\u5bb6'},
        ),
        migrations.RenameField(
            model_name='cooperativeentity',
            old_name='entirely_print',
            new_name='all_print',
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[(b'0501|0502|0503|0504', '\u9910\u996e\u573a\u6240'), (b'1906', '\u6807\u5fd7\u6027\u5efa\u7b51\u7269'), (b'1907', '\u70ed\u70b9\u5730\u540d'), (b'1905', '\u5e02\u4e2d\u5fc3'), (b'01|02|03', '\u6c7d\u8f66\u76f8\u5173'), (b'20', '\u516c\u5171\u8bbe\u65bd'), (b'1502', '\u706b\u8f66\u7ad9'), (b'1503', '\u6e2f\u53e3\u7801\u5934'), (b'1501', '\u673a\u573a\u76f8\u5173'), (b'1506', '\u8f7b\u8f68\u7ad9'), (b'1507', '\u516c\u4ea4\u8f66\u7ad9'), (b'1504', '\u957f\u9014\u6c7d\u8f66\u7ad9'), (b'1505', '\u5730\u94c1\u7ad9'), (b'1508', '\u73ed\u8f66\u7ad9'), (b'1509', '\u505c\u8f66\u573a'), (b'060101', '\u8d2d\u7269\u4e2d\u5fc3'), (b'060103', '\u514d\u7a0e\u54c1\u5e97'), (b'060102', '\u666e\u901a\u5546\u573a'), (b'0614', '\u4e2a\u4eba\u7528\u54c1/\u5316\u5986\u54c1\u5e97'), (b'13', '\u653f\u5e9c\u673a\u6784\u53ca\u793e\u4f1a\u56e2\u4f53'), (b'17', '\u516c\u53f8\u4f01\u4e1a'), (b'16', '\u91d1\u878d\u4fdd\u9669\u670d\u52a1'), (b'18', '\u9053\u8def\u9644\u5c5e\u8bbe\u65bd'), (b'0801', '\u4f53\u80b2\u4f11\u95f2\u670d\u52a1'), (b'0602', '\u4fbf\u6c11\u5546\u5e97/\u4fbf\u5229\u5e97'), (b'0603', '\u5bb6\u7535\u7535\u5b50\u5356\u573a'), (b'1102', '\u98ce\u666f\u540d\u80dc'), (b'0607', '\u7efc\u5408\u5e02\u573a'), (b'0604', '\u8d85\u7ea7\u5e02\u573a'), (b'1101', '\u516c\u56ed\u5e7f\u573a'), (b'1411', '\u4f20\u5a92\u673a\u6784'), (b'1412', '\u5b66\u6821'), (b'1413', '\u79d1\u7814\u673a\u6784'), (b'1414', '\u57f9\u8bad\u673a\u6784'), (b'1415', '\u9a7e\u6821'), (b'1201', '\u4ea7\u4e1a\u56ed\u533a'), (b'1203', '\u4f4f\u5b85\u533a'), (b'1202', '\u697c\u5b87'), (b'07', '\u751f\u6d3b\u670d\u52a1'), (b'04', '\u6469\u6258\u8f66\u670d\u52a1'), (b'0606', '\u5bb6\u5c45\u5efa\u6750\u5e02\u573a'), (b'0612', '\u4e13\u5356\u5e97'), (b'0611', '\u670d\u88c5\u978b\u5e3d\u76ae\u5177\u5e97'), (b'0610', '\u7279\u8272\u5546\u4e1a\u8857'), (b'1401|1402|1403|1404|1405|1406|1407', '\u79d1\u6559\u6587\u5316\u573a\u9986'), (b'0605', '\u82b1\u9e1f\u9c7c\u866b\u5e02\u573a'), (b'0901', '\u533b\u7597\u4fdd\u5065\u670d\u52a1'), (b'0505|0506|0507|0508|0509', '\u4f11\u95f2\u9910\u996e\u573a\u6240'), (b'1510', '\u8fc7\u5883\u53e3\u5cb8'), (b'0608|0609', '\u6587\u4f53\u7528\u54c1\u5e97'), (b'1002', '\u65c5\u9986\u62db\u5f85\u6240'), (b'1001', '\u5bbe\u9986\u9152\u5e97')], default=b'convenience_store', max_length=30, verbose_name='\u7c7b\u522b'),
        ),
    ]
