# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20160921_1819'),
        ('store', '0036_auto_20160908_1519'),
    ]

    operations = [
    ]
