# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0037_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.FloatField(verbose_name='\u8fdb\u8d27\u4ef7\u683c')),
                ('inventory', models.BigIntegerField(verbose_name='\u5e93\u5b58')),
                ('store_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.StoreItem', verbose_name='\u5546\u5e97\u5546\u54c1')),
            ],
            options={
                'verbose_name': 'StoreItemInventory',
                'verbose_name_plural': 'StoreItemInventorys',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='keeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5e97\u4e3b'),
        ),
    ]
