# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20161012_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeiteminventory',
            name='inventory',
            field=models.FloatField(verbose_name='\u5e93\u5b58'),
        ),
    ]
