# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0041_thirdpartydbinfo_thirdpartydbtables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_mch_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5fae\u4fe1\u652f\u4ed8\u5546\u6237\u53f7')),
                ('wechat_appid', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5fae\u4fe1\u516c\u4f17\u8d26\u53f7APPID')),
                ('wechat_username', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5fae\u4fe1\u5546\u6237\u5e73\u53f0\u767b\u5f55\u8d26\u53f7')),
                ('wechat_password', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5fae\u4fe1\u5546\u6237\u5e73\u53f0\u767b\u5f55\u5bc6\u7801')),
                ('wechat_api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5fae\u4fe1\u5546\u6237\u5e73\u53f0Api\u5bc6\u94a5')),
                ('alipay_username', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u652f\u4ed8\u5b9d\u7528\u6237\u540d')),
                ('alipay_password', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u652f\u4ed8\u5b9d\u767b\u5f55\u5bc6\u7801')),
                ('alipay_pid', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u652f\u4ed8\u5b9d\u5408\u4f5c\u8005\u8eab\u4efd(PID)')),
                ('alipay_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u652f\u4ed8\u5b9d\u5b89\u5168\u6821\u9a8c\u7801(KEY)')),
                ('alipay_appid', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u652f\u4ed8\u5b9dAPPID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5546\u5e97\u4ea4\u6613\u8d26\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u5546\u5e97\u4ea4\u6613\u8d26\u6237\u4fe1\u606f',
            },
        ),
    ]
