# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_transactionaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
