# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_auto_20161017_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartydbinfo',
            name='dbname',
            field=models.CharField(max_length=50, null=True, verbose_name='\u6570\u636e\u5e93\u540d'),
        ),
        migrations.AlterField(
            model_name='thirdpartydbtables',
            name='trigger_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
