# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20161018_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdp', models.BigIntegerField(null=True, verbose_name='\u603bGDP(\u5143)')),
                ('residents', models.IntegerField(null=True, verbose_name='\u5e38\u4f4f\u4eba\u53e3(\u4eba)')),
                ('area', models.IntegerField(null=True, verbose_name='\u533a\u57df\u9762\u79ef(km\xb2)')),
                ('population_density', models.IntegerField(null=True, verbose_name='\u4eba\u53e3\u5bc6\u5ea6(\u4eba/km\xb2)')),
                ('pgdp', models.IntegerField(null=True, verbose_name='\u4eba\u5747GDP(\u5143)')),
                ('district', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.City', verbose_name='\u533a\u57df')),
            ],
            options={
                'verbose_name': '\u533a\u57df\u8be6\u60c5',
                'verbose_name_plural': '\u533a\u57df\u8be6\u60c5',
            },
        ),
    ]
