# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_districtinfo'),
        ('store', '0046_auto_20161021_2052'),
    ]

    operations = [
    ]
