# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0037_auto_20161024_1352'),
        ('store', '0047_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='std_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='standard.Category', verbose_name='\u6807\u51c6\u5206\u7c7b'),
        )
    ]
