# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 07:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0048_auto_20161024_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 24, 7, 5, 21, 312620, tzinfo=utc), verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storecategory',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_store_categories', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u6838\u54e1'),
        ),
    ]
