# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_auto_20161024_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='chainstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.ChainStore', verbose_name='\u8fde\u9501\u5e97'),
        )
    ]
