# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20161024_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='foreign_id',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='\u7b2c\u4e09\u65b9\u6570\u636e\u5e93\u539f\u59cbid'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u5546\u5e97\u5206\u7c7b'),
        ),
    ]
