# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_auto_20161101_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_type', models.CharField(db_index=True, max_length=100, verbose_name='\u5c5e\u6027\u7c7b\u522b')),
                ('name', models.CharField(max_length=100, verbose_name='\u5c5e\u6027\u540d\u79f0')),
                ('chainstore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.ChainStore', verbose_name='\u8fde\u9501\u5e97')),
            ],
            options={
                'verbose_name': '\u5546\u5e97\u5c5e\u6027',
                'verbose_name_plural': '\u5546\u5e97\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='AttributeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.Attribute', verbose_name='\u5c5e\u6027')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
        ),
    ]
