# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_attribute_foreign_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('attr_type', 'name', 'chainstore')]),
        ),
    ]
