# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_auto_20161106_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
