# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_store_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='\u5546\u5e97\u5730\u5740'),
        ),
    ]
