# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_auto_20161106_1608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributemap',
            unique_together=set([('store', 'attribute')]),
        ),
    ]
