# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_auto_20161106_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='store_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='store.StoreCategory', verbose_name='\u5546\u54c1\u7c7b\u522b'),
        ),
    ]
