# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_storeitem_store_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='chain_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_store_items', to='store.ChainStore', verbose_name='\u8fde\u9501\u5e97'),
        ),
    ]
