# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_storeitem_chain_store'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeitem',
            unique_together=set([('store', 'chain_store', 'name')]),
        ),
    ]
