# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_auto_20161107_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDailyTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('sales', models.FloatField(verbose_name='\u9500\u552e\u989d')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_targets', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
            options={
                'verbose_name': '\u65e5\u9500\u552e\u4efb\u52a1',
                'verbose_name_plural': '\u65e5\u9500\u552e\u4efb\u52a1',
            },
        ),
    ]
