# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_storedailytarget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storedailytarget',
            unique_together=set([('date', 'store')]),
        ),
    ]
