# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorbarcodes',
            options={'verbose_name': '\u54c1\u724c\u5546\u54c1\u76d1\u6d4b\u7ba1\u7406', 'verbose_name_plural': '\u54c1\u724c\u5546\u54c1\u76d1\u6d4b\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='monitorbarcodes',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u7d50\u675f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='monitorbarcodes',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65e5\u671f'),
        ),
    ]
