# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0002_auto_20160712_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='customitem',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_items', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6236'),
            preserve_default=False,
        ),
    ]
