# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.PositiveIntegerField(verbose_name='\u6700\u5f8c\u66f4\u65b0ID')),
                ('count', models.PositiveIntegerField(verbose_name='\u91cf')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u5546\u5e97\u5546\u54c1\u540c\u6b65\u8bb0\u5f55',
                'verbose_name_plural': '\u5546\u5e97\u5546\u54c1\u540c\u6b65\u8bb0\u5f55',
            },
        ),
    ]
