# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synclog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitemsynclog',
            name='last_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='\u6700\u5f8c\u66f4\u65b0ID'),
        ),
    ]
