# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synclog', '0003_barcodestoreitemsynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebFoodSafetyBarcodeSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.PositiveIntegerField(unique=True, verbose_name='\u6700\u5f8c\u66f4\u65b0\u65e5\u671f')),
                ('count', models.PositiveIntegerField(verbose_name='\u91cf')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u98df\u54c1\u5b89\u5168\u7db2\u7ad9\u689d\u78bc\u540c\u6b65\u8bb0\u5f55',
                'verbose_name_plural': '\u98df\u54c1\u5b89\u5168\u7db2\u7ad9\u689d\u78bc\u540c\u6b65\u8bb0\u5f55',
            },
        ),
    ]
