# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synclog', '0004_webfoodsafetybarcodesynclog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webfoodsafetybarcodesynclog',
            name='last_date',
        ),
    ]
