# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('synclog', '0005_remove_webfoodsafetybarcodesynclog_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfoodsafetybarcodesynclog',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 5, 39, 11, 711493, tzinfo=utc), unique=True, verbose_name='\u6700\u5f8c\u66f4\u65b0\u65e5\u671f'),
            preserve_default=False,
        ),
    ]
