# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synclog', '0006_webfoodsafetybarcodesynclog_last_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, verbose_name=b'\xe6\x9d\xa5\xe6\xba\x90')),
                ('area', models.CharField(max_length=255, verbose_name=b'\xe5\x9c\xb0\xe5\x8c\xba')),
                ('crawl_date', models.DateField(verbose_name=b'\xe7\x88\xac\xe5\x8f\x96\xe6\x97\xa5\xe6\x9c\x9f')),
                ('tag', models.CharField(max_length=255, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe')),
                ('count', models.IntegerField(verbose_name=b'\xe6\x95\xb0\xe9\x87\x8f')),
            ],
            options={
                'verbose_name': '\u722c\u866b\u540c\u6b65\u8bb0\u5f55',
                'verbose_name_plural': '\u722c\u866b\u540c\u6b65\u8bb0\u5f55',
            },
        ),
    ]
