# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5206\u7c7b')),
                ('level', models.PositiveIntegerField(verbose_name='\u5c42')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65e5\u671f')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='standard.Category', verbose_name='\u4e0a\u7ea7\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='StandardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'pending_review', '\u5f85\u5ba1\u6838'), (b'human_verified', '\u5df2\u901a\u8fc7\u4eba\u5de5\u5ba1\u6838'), (b'auto_verified', '\u5df2\u901a\u8fc7\u81ea\u52a8\u5ba1\u6838')], default=b'under_review', max_length=100, verbose_name='\u72b6\u6001')),
                ('barcode', models.CharField(max_length=20, unique=True, verbose_name='\u56fd\u9645\u6761\u7801')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='\u5546\u54c1\u540d')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u89c4\u683c')),
                ('flavor', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53e3\u5473')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6700\u5e95\u5c42\u5206\u7c7b')),
                ('category_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5206\u7c7b ID \u8def\u5f84')),
                ('brand', models.CharField(max_length=255, verbose_name='\u54c1\u724c\u5546')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5173\u952e\u8bcd')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u6807\u51c6\u5546\u54c1',
                'verbose_name_plural': '\u6807\u51c6\u5546\u54c1',
            },
        ),
    ]
