# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 03:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_auto_20160621_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarditem',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None, verbose_name='\u5173\u952e\u8bcd'),
        ),
        migrations.AddField(
            model_name='standarditem',
            name='num_matches',
            field=models.PositiveIntegerField(default=0, verbose_name='\u5339\u914d\u5546\u54c1\u6570'),
            preserve_default=False,
        ),
    ]
