# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 05:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standard', '0007_auto_20160623_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarditem',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_standard_items', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u6838\u54e1'),
        ),
    ]
