# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0008_standarditem_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standarditem',
            old_name='category',
            new_name='category_old',
        ),
        migrations.RemoveField(
            model_name='standarditem',
            name='category_path',
        ),
    ]
