# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_auto_20160624_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarditem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='standard.Category', verbose_name='\u5206\u7c7b'),
        ),
    ]
