# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 05:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0010_standarditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarditem',
            name='mean',
            field=models.FloatField(null=True, verbose_name='\u5e73\u5747\u552e\u4ef7'),
        ),
        migrations.AddField(
            model_name='standarditem',
            name='std_dev',
            field=models.FloatField(null=True, verbose_name='Std Dev'),
        ),
        migrations.AddField(
            model_name='standarditem',
            name='store_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), null=True, size=None, verbose_name='\u4fbf\u5229\u5e97\u552e\u4ef7'),
        ),
        migrations.AlterField(
            model_name='standarditem',
            name='status',
            field=models.CharField(choices=[(b'pending_review', '\u5f85\u5ba1\u6838'), (b'half_verified', '\u534a\u5ba1\u6838'), (b'human_verified', '\u5df2\u901a\u8fc7\u4eba\u5de5\u5ba1\u6838'), (b'auto_verified', '\u5df2\u901a\u8fc7\u81ea\u52a8\u5ba1\u6838')], default=b'human_verified', max_length=100, verbose_name='\u72b6\u6001'),
        ),
    ]
