# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standard', '0011_auto_20160629_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20, unique=True, verbose_name='\u56fd\u9645\u6761\u7801')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='\u5382\u5546')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65e5\u671f')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_standard_vendors', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u6838\u54e1')),
            ],
        ),
    ]
