# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0013_standardvendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardvendor',
            name='num_sku',
            field=models.PositiveIntegerField(default=0, verbose_name='SKU'),
            preserve_default=False,
        ),
    ]
