# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0015_auto_20160702_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardvendor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5382\u5546'),
        ),
    ]
