# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0016_auto_20160702_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardvendor',
            options={'verbose_name': '\u56fd\u6761\u54c1\u724c\u7801', 'verbose_name_plural': '\u56fd\u6761\u54c1\u724c\u7801'},
        ),
        migrations.AddField(
            model_name='standardvendor',
            name='standard_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f01\u4e1a\u540d'),
        ),
    ]
