# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standard', '0019_auto_20160704_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardVendorSeriesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'pending_review', '\u5f85\u5ba1\u6838'), (b'human_verified', '\u5df2\u901a\u8fc7\u4eba\u5de5\u5ba1\u6838')], default=b'pending_review', max_length=100, verbose_name='\u72b6\u6001')),
                ('vendor_short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f01\u4e1a\u7b80\u79f0')),
                ('series', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7cfb\u5217')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65e5\u671f')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_series', to='standard.Category', verbose_name='\u5206\u7c7b')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_vendor_series_category', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u6838\u54e1')),
            ],
            options={
                'verbose_name': '\u4f01\u4e1a-\u7cfb\u5217-\u7c7b\u5225',
                'verbose_name_plural': '\u4f01\u4e1a-\u7cfb\u5217-\u7c7b\u5225',
            },
        ),
    ]
