# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0021_auto_20160704_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarditem',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='standard.StandardSeries', verbose_name='\u7cfb\u5217'),
        ),
    ]
