# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0023_auto_20160705_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardvendor',
            options={'verbose_name': '\u54c1\u724c\u7801', 'verbose_name_plural': '\u54c1\u724c\u7801'},
        ),
        migrations.AlterField(
            model_name='standardvendor',
            name='status',
            field=models.CharField(choices=[(b'new', '\u65b0\u589e\u6761\u7801'), (b'pending_review', '\u5f85\u5ba1\u6838'), (b'human_verified', '\u5df2\u901a\u8fc7\u4eba\u5de5\u5ba1\u6838'), (b'na', '\u4e0d\u5904\u7406')], default=b'pending_review', max_length=100, verbose_name='\u72b6\u6001'),
        ),
    ]
