# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0025_auto_20160705_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f01\u4e1a\u7b80\u79f0')),
                ('num_vendors', models.PositiveIntegerField(default=0, verbose_name='\u751f\u7522\u5382\u5546\u6570')),
                ('num_sku', models.PositiveIntegerField(default=0, verbose_name='SKU')),
                ('num_pending_items', models.PositiveIntegerField(default=0, verbose_name='\u5f85\u5ba1\u6838\u5546\u54c1\u6570')),
                ('num_verified_items', models.PositiveIntegerField(default=0, verbose_name='\u6807\u54c1\u6570')),
                ('num_na', models.PositiveIntegerField(default=0, verbose_name='\u4e0d\u5904\u7406')),
                ('num_new', models.PositiveIntegerField(default=0, verbose_name='\u65b0\u54c1\u6570')),
                ('complete_rate', models.FloatField(default=0, verbose_name='\u5b8c\u6210\u5ea6')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65e5\u671f')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u516c\u53f8',
                'verbose_name_plural': '\u516c\u53f8',
            },
        ),
    ]
