# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0027_auto_20160706_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardcompany',
            options={'verbose_name': '\u4f01\u4e1a', 'verbose_name_plural': '\u4f01\u4e1a'},
        ),
        migrations.AlterField(
            model_name='standarditem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='standard.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='standarditem',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='standard.StandardSeries', verbose_name='\u7cfb\u5217'),
        ),
    ]
