# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 05:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0028_auto_20160707_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardcompany',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='\u5173\u952e\u8bcd'),
        ),
    ]
