# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0030_standardcompany_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarditem',
            name='status',
            field=models.CharField(choices=[(b'new', '\u65b0\u589e\u6807\u54c1'), (b'pending_review', '\u5f85\u5ba1\u6838'), (b'half_verified', '\u534a\u5ba1\u6838'), (b'human_verified', '\u5df2\u901a\u8fc7\u4eba\u5de5\u5ba1\u6838'), (b'auto_verified', '\u5df2\u901a\u8fc7\u81ea\u52a8\u5ba1\u6838'), (b'na', '\u4e0d\u5904\u7406')], default=b'human_verified', max_length=100, verbose_name='\u72b6\u6001'),
        ),
    ]
