# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0030_standardcompany_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True, verbose_name='\u6807\u7b7e')),
                ('type', models.CharField(choices=[(b'brand', '\u54c1\u724c'), (b'category', '\u5206\u985e'), (b'property', '\u5c5e\u6027')], max_length=100, verbose_name='\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u6807\u51c6\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u51c6\u6807\u7b7e',
            },
        ),
        migrations.AlterField(
            model_name='standarditem',
            name='status',
            field=models.CharField(choices=[(b'new', '\u65b0\u589e\u6807\u54c1'), (b'pending_review', '\u5f85\u5ba1\u6838'), (b'half_verified', '\u534a\u5ba1\u6838'), (b'human_verified', '\u5df2\u901a\u8fc7\u4eba\u5de5\u5ba1\u6838'), (b'auto_verified', '\u5df2\u901a\u8fc7\u81ea\u52a8\u5ba1\u6838'), (b'na', '\u4e0d\u5904\u7406')], default=b'human_verified', max_length=100, verbose_name='\u72b6\u6001'),
        ),
    ]
