# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0031_auto_20160923_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardtag',
            name='pinyin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u62fc\u97f3'),
        ),
        migrations.AlterField(
            model_name='standardtag',
            name='type',
            field=models.CharField(choices=[(b'brand', '\u54c1\u724c'), (b'category', '\u5546\u54c1\u5206\u7c7b'), (b'property', '\u5546\u54c1\u5c5e\u6027'), (b'quantity', '\u5546\u54c1\u6570\u91cf'), (b'ignore', '\u5ffd\u7565')], max_length=100, verbose_name='\u7c7b\u522b'),
        ),
    ]
