# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 07:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0032_auto_20160927_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardtag',
            name='alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='\u522b\u540d'),
        ),
    ]
