# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0031_auto_20160830_1656'),
        ('standard', '0034_standardtag_created_at'),
    ]

    operations = [
    ]
