# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_auto_20160531_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStoreCategorySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('category', models.CharField(max_length=255, verbose_name='\u5206\u7c7b')),
                ('sales', models.FloatField(verbose_name='\u9500\u552e\u989d')),
                ('num', models.FloatField(verbose_name='\u9500\u91cf')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_summary', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStoreItemSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('sales', models.FloatField(verbose_name='\u9500\u552e\u989d')),
                ('num', models.FloatField(verbose_name='\u9500\u91cf')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u89c4\u683c')),
                ('flavor', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53e3\u5473')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6700\u5e95\u5c42\u5206\u7c7b')),
                ('barcode', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='\u56fd\u9645\u6761\u7801')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='store.StoreItem', verbose_name='\u5546\u54c1')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStoreSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('num_sku', models.PositiveSmallIntegerField(verbose_name='\u8ce3\u51faSKU')),
                ('sales', models.FloatField(verbose_name='\u9500\u552e\u989d')),
                ('num', models.FloatField(verbose_name='\u9500\u91cf')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
        ),
        # migrations.CreateModel(
        #     name='MonthlyStoreItemPattern',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('date', models.DateField(verbose_name='\u65e5\u671f')),
        #         ('patterns', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
        #         ('frequency', models.PositiveIntegerField(verbose_name='\u9891\u6b21')),
        #         ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_patterns', to='store.Store', verbose_name='\u5546\u5e97')),
        #     ],
        # ),
    ]
