# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_auto_20160531_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailystoreitemsummary',
            options={'verbose_name': '\u4fbf\u5229\u5e97\u6bcf\u5929\u5355\u54c1\u6c47\u603b', 'verbose_name_plural': '\u4fbf\u5229\u5e97\u6bcf\u5929\u5355\u54c1\u6c47\u603b'},
        ),
        migrations.AddField(
            model_name='dailystorecategorysummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 31, 8, 2, 22, 47948, tzinfo=utc), verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailystoreitemsummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 31, 8, 2, 27, 674854, tzinfo=utc), verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailystoresummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 31, 8, 2, 32, 791389, tzinfo=utc), verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        )
    ]
