# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20160531_1731'),
        ('summary', '0004_dailystoreitemsummary_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStoreCategorySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(verbose_name='\u65e5\u671f(yyyymm)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('category', models.CharField(max_length=255, verbose_name='\u5206\u7c7b')),
                ('sales', models.FloatField(verbose_name='\u9500\u552e\u989d')),
                ('num', models.FloatField(verbose_name='\u9500\u91cf')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_category_summary', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStoreItemSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(verbose_name='\u65e5\u671f(yyyymm)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('sales', models.FloatField(verbose_name='\u9500\u552e\u989d')),
                ('num', models.FloatField(verbose_name='\u9500\u91cf')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u89c4\u683c')),
                ('flavor', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53e3\u5473')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6700\u5e95\u5c42\u5206\u7c7b')),
                ('barcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u56fd\u9645\u6761\u7801')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summary', to='store.StoreItem', verbose_name='\u5546\u54c1')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_item_summary', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
            options={
                'verbose_name': '\u4fbf\u5229\u5e97\u6bcf\u6708\u5355\u54c1\u6c47\u603b',
                'verbose_name_plural': '\u4fbf\u5229\u5e97\u6bcf\u6708\u5355\u54c1\u6c47\u603b',
            },
        ),
        migrations.AlterField(
            model_name='dailystoreitemsummary',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u56fd\u9645\u6761\u7801'),
        ),
    ]
