# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20160531_1731'),
        ('summary', '0005_auto_20160606_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStoreItemPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(verbose_name='\u65e5\u671f(yyyymm)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('patterns', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('frequency', models.PositiveIntegerField(verbose_name='\u9891\u6b21')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_patterns', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
        ),
    ]
