# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_auto_20160613_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailystoreitemsummary',
            unique_together=set([('date', 'store', 'item')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailystoresummary',
            unique_together=set([('date', 'store')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystorecategorysummary',
            unique_together=set([('date', 'store', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystoreitempattern',
            unique_together=set([('date', 'store')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystoreitemsummary',
            unique_together=set([('date', 'store', 'item')]),
        ),
    ]
