# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160616_1809'),
        ('summary', '0008_auto_20160613_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStoreSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(verbose_name='\u65e5\u671f(yyyymm)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('num_sku', models.PositiveSmallIntegerField(verbose_name='\u552f\u4e00\u5546\u54c1\u6570')),
                ('sales', models.FloatField(verbose_name='\u9500\u552e\u989d')),
                ('num', models.FloatField(verbose_name='\u9500\u91cf')),
                ('num_trades', models.FloatField(verbose_name='\u4ea4\u6613\u6570')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summary', to='store.Store', verbose_name='\u5546\u5e97')),
            ],
        ),
        migrations.AddField(
            model_name='dailystoresummary',
            name='num_trades',
            field=models.FloatField(default=0, verbose_name='\u4ea4\u6613\u6570'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailystoresummary',
            name='num_sku',
            field=models.PositiveSmallIntegerField(verbose_name='\u552f\u4e00\u5546\u54c1\u6570'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystoresummary',
            unique_together=set([('date', 'store')]),
        ),
    ]
