# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_auto_20160616_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystoresummary',
            name='num_trades',
            field=models.FloatField(null=True, verbose_name='\u4ea4\u6613\u6570'),
        ),
        migrations.AlterField(
            model_name='monthlystoresummary',
            name='num_trades',
            field=models.FloatField(null=True, verbose_name='\u4ea4\u6613\u6570'),
        ),
    ]
