# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_auto_20160625_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystorecategorysummary',
            name='category_id',
            field=models.PositiveIntegerField(null=True, verbose_name='\u5206\u7c7bID'),
        ),
        migrations.AddField(
            model_name='dailystoreitemsummary',
            name='category_id',
            field=models.PositiveIntegerField(null=True, verbose_name='\u5206\u7c7bID'),
        ),
        migrations.AddField(
            model_name='monthlystorecategorysummary',
            name='category_id',
            field=models.PositiveIntegerField(null=True, verbose_name='\u5206\u7c7bID'),
        ),
        migrations.AddField(
            model_name='monthlystoreitemsummary',
            name='category_id',
            field=models.PositiveIntegerField(null=True, verbose_name='\u5206\u7c7bID'),
        ),
        migrations.AlterUniqueTogether(
            name='dailystorecategorysummary',
            unique_together=set([('date', 'store', 'category_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystorecategorysummary',
            unique_together=set([('date', 'store', 'category_id')]),
        ),
    ]
