# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0013_auto_20160701_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystoreitemsummary',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='monthlystoreitemsummary',
            name='category_id',
        ),
    ]
