# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0014_auto_20160711_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystoreitemsummary',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53e3\u5473'),
        ),
        migrations.AddField(
            model_name='monthlystoreitemsummary',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53e3\u5473'),
        ),
    ]
