# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0021_auto_20160722_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlystoreitempattern',
            options={'verbose_name': '\u540c\u65f6\u8d2d\u4e70\u5546\u54c1', 'verbose_name_plural': '\u540c\u65f6\u8d2d\u4e70\u5546\u54c1'},
        ),
        migrations.AlterField(
            model_name='monthlystoreitempattern',
            name='date',
            field=models.IntegerField(verbose_name='\u65e5\u671f'),
        ),
    ]
